spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/crowdpulse
spring.datasource.username=root
spring.datasource.password=Root@123
server.port=8081

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.redis.host=localhost
spring.redis.port=6379

